baseURL = 'https://blog.mark4p.top'
languageCode = 'pt-br'
title = 'Blog do Cássio'
theme = 'PaperMod'
defaultContentLanguage = 'pt-br'
enableRobotsTXT = true


[menu]
  [[menu.main]]
    name = "Pesquisar"
    url = "search"
    weight = 10
  [[menu.main]]
    name = "Início"
    url = "https://mark4p.top"
    weight = 10

[params]
  # ======================
  # Configurações Gerais
  # ======================
  defaultTheme = "auto"
  description = "Blog do Cássio"
  editURL = "https://github.com/AngryPlayer04/blog/edit/main/content/" # Opcional: link para edição
  ogImage = "/static/logo.png"
  env = "production"
[params.assets]
  favicon = "/static/logo.png"
  # ======================
  # HomeInfo (Seção de Boas-Vindas)
  # ======================
  [params.homeInfoParams]
    Title = "Bem vindo(a)! 👋"
    Content = "Este é o meu blog, criado com o intuito de anotar o que faço na área de tecnologia."
    ShowHomeButtons = true # Botões abaixo do texto
    ShowShareButtons = true # Botões de compartilhamento
    
    [[params.homeInfoParams.buttons]]
      name = "Início"
      url = "https://cassionhieg.live"
      icon = "fa-home"
      weight = 1
    
    [[params.homeInfoParams.buttons]]
      name = "GitHub"
      url = "https://github.com/AngryPlayer04"
      icon = "fa-github"
      weight = 2

  [params.article]
    ShowShareButtons = true  # Para artigos/posts
    ShowToc = true

  [params.share]
    enable = true
    Twitter = true
    Linkedin = true
    WhatsApp = true
    Telegram = true

  # ======================
  # Capas dos Posts
  # ======================
  [params.cover]
    hidden = true
    # default = "/images/default-cover.jpg"
    hiddenInList = false
    responsiveImages = true # Ativa redimensionamento automático

  # ======================
  # Configuração de Pesquisa
  # ======================
  [params.search]
    enable = true
    type = "json"
    placeholder = "Pesquisar posts..."
    maxResults = 5
    [params.search.advanced]
      includeContent = true 

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[outputFormats]
  [outputFormats.JSON]
    baseName = "rss"
    

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Permite HTML raw quando necessário
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      autoHeadingID = true # IDs automáticos para cabeçalhos

[imaging]
  quality = 85 # Qualidade das imagens processadas
  resampleFilter = "Lanczos" # Algoritmo de redimensionamento

